# Make sure to check the documentation at http://goreleaser.com
env:
  - GO_VERSION=1.17.5
before:
  hooks:
    - go mod download
builds:
  - id: "ktctl"
    main: ./cmd/ktctl/main.go
    binary: ktctl
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
  - id: "shadow"
    main: ./cmd/shadow/main.go
    binary: shadow
    goos:
      - linux
    goarch:
      - amd64
  - id: "router"
    main: ./cmd/router/main.go
    binary: router
    goos:
      - linux
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - shadow
    image_templates:
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:latest"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:{{ .Tag }}"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:v{{ .Major }}"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:v{{ .Version }}"
    dockerfile: build/docker/shadow/Dockerfile_releaser
    skip_push: false
    extra_files:
      - build/docker/shadow/run.sh
  - goos: linux
    goarch: amd64
    ids:
      - router
    image_templates:
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-router:latest"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-router:{{ .Tag }}"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-router:v{{ .Major }}"
      - "registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-router:v{{ .Version }}"
    dockerfile: build/docker/router/Dockerfile_releaser
    skip_push: false
    extra_files:
      - build/docker/router/nginx.conf
archives:
  - id: ktctl
    builds:
      - ktctl
    name_template: 'ktctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
        }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: alibaba
    name: kt-connect
  ids:
    - ktctl
  # @see https://github.com/goreleaser/goreleaser/issues/1023
  draft: false
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
