apiVersion: v1
kind: Service
metadata:
  name: kt-connect-dns
spec:
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: 53
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    kt-component: dns-server
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    kt-component: dns-server
  name: kt-connect-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      kt-component: dns-server
  template:
    metadata:
      labels:
        kt-component: dns-server
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/rdc-incubator/kt-connect-shadow:stable
        name: dns-server